### ISSUE TITLE
Lesbarkeit von Beiträgen (Yoast SEO) wird durch einfügen der Tabelle von Gut auf OK runtergestuft

### ISSUE THREAD

**Issue by luca19982** [TablePress/TablePress#169]
Hi. Erstmal danke für das Plugin. Nutze es seit einigen Monaten. Nach dem Update auf V2 wurde die Lesbarkeit aller Beiträge (YOAST SEO), von GUT auf OK zurückgestuft. Mit Version 1 gab es dieses Problem nicht. Ist es möglich, das Problem zu beheben?

**Comment by TobiasBg** [comment]
Hi,

vielen Dank für deine Meldung. Ich habe ehrlich gesagt keine Ahnung, worauf diese Einschätzung von YoastSEO beruht. Zwischen Version 1 und 2 von TablePress hat sich nichts am HTML-Code der Tabelle im Frontend geändert, daher weiß ich auch leider nicht, was man hier machen könnte. Ich kann daher nur vorschlagen, dass du dich damit an das YoastSEO-Team wendest.

Viele Grüße
Tobias

**Comment by luca19982** [comment]
Vielen Dank für die schnelle Rückmeldung. Dann werde ich das auch mal YOAST SEO melden. 

Ich habe es auch extra getestet. Nach dem Rollback auf 1.14 ist die Lesbarkeit GUT, ab 2.0 bis 2.03 ist die Lesbarkeit des selben Beitrags nur noch OK.
