### ISSUE TITLE
Question: posibility to get table information from a json REST api, instead of importing?

### ISSUE THREAD

**Issue by ctwhome** [TablePress/TablePress#170]
hi @TobiasBg 

I am trying to see if I can pull data from an URL, it doesn't have to be refreshed in real time, just when the WordPress page enters or refreshes. Is this something available in the plugin? 

I am unsure if the option importing (which works great) does it. I don't see how to edit later on the URL once the table is created.

Thanks so much already!

**Comment by TobiasBg** [comment]
Hi @ctwhome,

depending on whether the REST API returns a suitable JSON format, the "Automatic Periodic Table Import" module (see https://tablepress.org/modules/automatic-periodic-table-import/) that is available in the TablePress Max Premium plan, can probably help here.
It's an import, but you can have that triggered periodically, e.g. every 5 minutes or so, using a server cron job.
If the REST API does not yet provide a suitable table format, you could integrate an intermediate proxy script that reformats the data structure.

Regards,
Tobias

**Comment by ctwhome** [comment]
thanks for the fast response. We manage the API endpoint which is handy. I assume that the import triggered by the cron job also belongs to the Max premium plan?

**Comment by TobiasBg** [comment]
Hi,

the logic for the automatic periodic import is in TablePress Max, indeed. The server cron job is technically not needed, but will greatly increase reliability, as the otherwise used WordPress Cron system has a few disadvantages.

Regards,
Tobias
