### ISSUE TITLE
Can't save Auto Import Tables config

### ISSUE THREAD

**Issue by dorogoff** [TablePress/TablePress#171]
Hi, not sure is it issue, but it breaks user experience, in a case you want to save a config (for any reason) and hit **Save Auto Import Configuration** button, you got the error about required fields. But I just want change the period for auto import, and can't while fiel is not selected at the top panel. 

https://prnt.sc/Yf2ahiutJPfR

Suggest to add somethine like this to view-auto-import.php

```
public function _add_footer_js() {
...
$('#tables-import-file-upload').attr('required', false);
...
```

Thanks!

**Comment by TobiasBg** [comment]
Hi @dorogoff,

I already have a fixed version for this. Please get in touch via email (the address is on https://tablepress.org/impressum/ ) and I will send it to you.

Best wishes,
Tobias
