### ISSUE TITLE
Function WP_Block_Type_Registry::register was called incorrectly

### ISSUE THREAD

**Issue by danieldekay** [TablePress/TablePress#172]
We have a website using Elementor, and we use three tables on one page. The debug log of Wordpress shows the following log entry, 6 times (I suspect 2 times for each of the 3 tables).

Function WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type "tablepress/table" is already registered. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.)
Line : 5835
/wp-includes/functions.php

**Comment by TobiasBg** [comment]
Hi @danieldekay,

thanks for your report. I'm not sure what exactly is causing this, but my assumption is that this is actually triggered by either your theme or another plugin. I can not reproduce on my tests sites and haven't received similar reports yet. Also, TablePress only loads that block once, so most likely something is then loading TablePress multiple times (probably in a wrong way).
Can you therefore please try again after temporarily deactivating all other plugins and after switching to a WordPress default theme like Twenty Twenty?

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

without further information, I can't see how this could be caused by TablePress. If there are new results, please feel free to reopen this.

Best wishes,
Tobias
