### ISSUE TITLE
Freemius integration is doing heavy damage to wp_sitemeta meta_key fs_accounts

### ISSUE THREAD

**Issue by moschlar** [TablePress/TablePress#175]
Hi there,

we are using open source TablePress on a busy multisite with a MariaDB Galera Cluster as a database backend.

I noted a huge amount of deadlocks occuring because apparently, the Freemius integration tries to update `wp_sitemeta` where `'meta_key' = 'fs_accounts'`

From a quick counting through the server logs, the deadlock occurs roughly 4000 times a day, probably in busy times.
I don't think this is affecting site visitors at all, but nevertheless.

Here's an exemplary error log entry:

> [29-Mar-2023 12:18:11 UTC] WordPress database error Deadlock found when trying to get lock; try restarting transaction for query UPDATE `jguwp1_sitemeta` SET `meta_value` = 'a:4:{s:21:\"id_slug_type_path_map\";a:1:{i:10340;a:3:{s:4:\"slug\";s:10:\"tablepress\";s:4:\"type\";s:6:\"plugin\";s:4:\"path\";s:25:\"tablepress/tablepress.php\";}}s:11:\"plugin_data\";a:1:{s:10:\"tablepress\";a:13:{s:16:\"plugin_main_file\";O:8:\"stdClass\":1:{s:4:\"path\";s:25:\"tablepress/tablepress.php\";}s:20:\"is_network_activated\";b:0;s:16:\"sdk_last_version\";s:5:\"2.5.3\";s:11:\"sdk_version\";s:5:\"2.5.5\";s:16:\"sdk_upgrade_mode\";b:1;s:18:\"sdk_downgrade_mode\";b:0;s:19:\"plugin_last_version\";s:3:\"2.1\";s:14:\"plugin_version\";s:5:\"2.0.4\";s:19:\"plugin_upgrade_mode\";b:0;s:21:\"plugin_downgrade_mode\";b:1;s:21:\"is_plugin_new_install\";b:0;s:17:\"was_plugin_loaded\";b:1;s:17:\"connectivity_test\";a:6:{s:12:\"is_connected\";N;s:4:\"host\";s:17:\"...\";s:9:\"server_ip\";s:13:\"...\";s:9:\"is_active\";b:1;s:9:\"timestamp\";i:1680090640;s:7:\"version\";s:3:\"2.1\";}}}s:13:\"file_slug_map\";a:1:{s:25:\"tablepress/tablepress.php\";s:10:\"tablepress\";}s:7:\"plugins\";a:1:{s:10:\"tablepress\";O:9:\"FS_Plugin\":24:{s:16:\"parent_plugin_id\";N;s:5:\"title\";s:10:\"TablePress\";s:4:\"slug\";s:10:\"tablepress\";s:12:\"premium_slug\";s:18:\"tablepress-premium\";s:4:\"type\";s:6:\"plugin\";s:20:\"affiliate_moderation\";b:0;s:19:\"is_wp_org_compliant\";b:1;s:22:\"premium_releases_count\";N;s:4:\"file\";s:25:\"tablepress/tablepress.php\";s:7:\"version\";s:3:\"2.1\";s:11:\"auto_update\";N;s:4:\"info\";N;s:10:\"is_premium\";b:0;s:14:\"premium_suffix\";s:9:\"(Premium)\";s:7:\"is_live\";b:1;s:9:\"bundle_id\";N;s:17:\"bundle_public_key\";N;s:17:\"opt_in_moderation\";N;s:10:\"public_key\";s:32:\"pk_b215ca1bb4041cf43ed137ae7665b\";s:10:\"secret_key\";N;s:2:\"id\";s:5:\"10340\";s:7:\"updated\";N;s:7:\"created\";N;s:22:\"\0FS_Entity\0_is_updated\";b:1;}}}' WHERE `site_id` = 1 AND `meta_key` = 'fs_accounts' made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/tablepress/tablepress.php'), tb_tp_fs, fs_dynamic_init, Freemius::instance, Freemius->__construct, Freemius->_version_updates_handler, FS_Storage->__set, FS_Key_Value_Storage->__set, FS_Key_Value_Storage->store, FS_Option_Manager->set_option, FS_Option_Manager->store, update_site_option, update_network_option

I don't know if this is something that's solvable by TablePress or Freemius, but maybe we can find solutions.

**Comment by moschlar** [comment]
Something strange is going on there - it is thinking the plugin is being downgraded:

`s:19:plugin_last_version";s:3:"2.1";s:14:"plugin_version";s:5:"2.0.4";`
`s:19:"plugin_upgrade_mode";b:0;s:21:"plugin_downgrade_mode";b:1;`

We are indeed using version 2.0.4 and not 2.1

**Comment by TobiasBg** [comment]
Hi @moschlar,

Thanks for your report!
TablePress doesn't do anything special regarding the integration of the Freemius SDK (especially in the sense of updating such meta keys). Thus, this is indeed something that would need to be looked at by the Freemius team.
I'll be sending their support team an email to make them aware of this!

Best wishes,
Tobias

**Comment by TobiasBg** [comment]
Hi @moschlar,

that downgrade thing is also strange. I don't know how those internals work, but as TablePress 2.1 also includes a new version of the Freemius SDK, it might be reasonable to update and check if those meta key issues persists after that.

Best wishes,
Tobias

**Comment by moschlar** [comment]
Okay, I'm so very sorry - apparently there was a development copy that used the same database that had been forgotten on the 2.1 upgrade...

Now we're using 2.1 really everywhere and I would suspect the issue to go away..

Really sorry for this wrong "accusation" :wink:

**Comment by TobiasBg** [comment]
Hi @moschlar,

no problem :-) I think what could have been going on here is that the two versions were "fighting" about who is right, updating those meta options back and forth.
If this turns out to happen only with TablePress 2.1 again, please feel free to reopen this :-)

Best wishes,
Tobias
