### ISSUE TITLE
check if file exists before attempting to unlink

### ISSUE THREAD

**Issue by jhard** [TablePress/TablePress#177]
In `tablepress/classes/class-import.php:361`
```
359         protected function _maybe_unlink_file( array $file ) {
360                 if ( ! isset( $file['keep_file'] ) || ! $file['keep_file'] ) {
361                         @unlink( $file['location'] );
362                 }
363         }
```
@ will locally set the error reporting level to 0, but error handlers will still be called.
This could be suppressed by adding a local error handler with `set_error_handler` (and setting back the original one afterwards), but the more straight forward and cleaner way would be to simply check that the file exists.
In my opinion, if the file does not exist, there should be no call to unlink, and if the file exists but cannot be deleted, something is broken and triggering an error/warning is the right thing to do. Since this code isn't dealing with expected race conditions, there should be no reason for the file to vanish between file_exists/is_file and unlink.

I cannot offer an actual reproduction, but users have been using the import feature (and it seems to have worked), but deletions failed: `Caught an error E_WARNING in /var/www/public/wp-content/plugins/tablepress/classes/class-import.php:361 unlink(/tmp/phpstve4j): No such file or directory`.

**Comment by TobiasBg** [comment]
Hi @jhard,

thanks for opening this issue! Indeed, the purpose of this file is to clean up after the import, to not leave no longer needed temporary files rotten on disk. Therefore, it's indeed possible (from what I remember, haven't checked the code paths) that this function is called "just to be sure" after bailing early when a file could not be read, for example.

I agree that adding a `file_exists()` check should work here. The outcome (the file is no longer there) is the same, and the performance overhead should be minimal, given that this is just one extra check.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @jhard,

I have added this change to the TablePress source repository. The change will be synced to this repo when the next release happens and released with that.

Thanks for reporting and suggesting this!

Best wishes,
Tobias
