### ISSUE TITLE
Error:  Function is_search was called incorrectly...

### ISSUE THREAD

**Issue by neurotools** [TablePress/TablePress#179]
Hello... I'm getting a **PHP Notice** from this plugin.

WordPress Version: 6.2.2
Plugin Version: 2.1.5
PHP: 7.4.30

`Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/documentation/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/example.com/wp-includes/functions.php on line 5865`

Function is_search() is called on line 889 of controllers/controller-frontend.php (function posts_search_filter).

Function posts_search_filter() is called in TablePress_Frontend_Controller constructor on line 66 of controllers/controller-frontend.php

**Comment by TobiasBg** [comment]
Hi @neurotools,

I have not yet seen this notice on my sites and have not received any other reports of this. Also, TablePress does not actually call `posts_search_filter` in the constructor of `TablePress_Frontend_Controller` but only adds it as a callback to the `posts_search` plugin filter hook.

Therefore, I assume that something else on the site (a plugin or maybe the search implementation in your theme) are running whatever functionality that then evaluates the `posts_search` filter hook too early. Can you maybe check that?

Regards,
Tobias

**Comment by neurotools** [comment]
I appreciate your feedback! I'll check (tomorrow) and comment back here.

**Comment by neurotools** [comment]
As you commented... It was a problem on the Template that causes the notice. Thanks!

**Comment by TobiasBg** [comment]
Hi @neurotools,

great to hear that you found the cause! Thanks for the update here!

Best wishes,
Tobias
