### ISSUE TITLE
Change Default Table Features for Site Visitors

### ISSUE THREAD

**Issue by Nolanlemahn** [TablePress/TablePress#180]
Hello - 

I am a hobbyist/volunteering and am enjoying the layout/simplicity of TablePress.

One question - 
![image](https://github.com/TablePress/TablePress/assets/8920847/e4eda1ed-810c-46ba-bd6a-8adbc757f12a)

This appears to be the default for new tables. We were hoping we could change the default to this:

![image](https://github.com/TablePress/TablePress/assets/8920847/04faf65a-a84d-48e8-9294-ab71352c6041)

- is there a plan to support changing default options in the future?
- if this was something we wanted to hack-in, could you point us to where that could be accomplished?

Thank you!

**Comment by TobiasBg** [comment]
Hi @Nolanlemahn,

I do not plan to add a user interface for this. Instead, you can use the `tablepress_table_template` plugin filter hook, defined at https://github.com/TablePress/TablePress/blob/6f7d3721c5d7ea2a41e3e386318832061f18629e/models/model-table.php#L838-L845 , for this.

Best wishes,
Tobias
