### ISSUE TITLE
No obvious way to disable/revert inline CSS loading

### ISSUE THREAD

**Issue by Nolanlemahn** [TablePress/TablePress#181]
Another thought - I noticed that depending on the setup, a user, when handling custom CSS, may see the following:

`To proceed without trying to save the “Custom CSS” to a file, click the button below. Your “Custom CSS” will then be loaded inline. `

Is there (or will there be) an option to retry FTP file write?

**Comment by TobiasBg** [comment]
Hi @Nolanlemahn,

the easiest way to trigger a re-save here should be to simply save the "Custom CSS" again (maybe after making some dummy change, to trigger an actual re-save).

Regards,
Tobias
