### ISSUE TITLE
Oops! That page can’t be found.

### ISSUE THREAD

**Issue by Commodoortje** [TablePress/TablePress#186]
Hi,

The table (xls) is not visible in edge browser
The error message "Oops! That page can't be found."
The table is properly visible in Chrome browser

https://eulinkonline.nl/overzicht-wandelingen/

Could it be that I am doing something wrong?
![image](https://github.com/TablePress/TablePress/assets/17632950/57999222-2e97-4356-86ca-a0b32b74de1f)

**Comment by TobiasBg** [comment]
Hi @Commodoortje,

Sorry to hear that you are having trouble with your site.
Now, I'm also getting that message with Chrome, so presumably it's something that's related to being logged-in vs. logged-out? This could for example be that this page is marked as "private" and not "public".
I don't think it's related to TablePress though.

Regards,
Tobias

**Comment by Commodoortje** [comment]
Thank you, 


![image](https://github.com/TablePress/TablePress/assets/17632950/5ba23612-f3ed-4473-a827-5b1efe1e8daa)

Thank you, this was indeed the problem.
Thanks for your advice

**Comment by TobiasBg** [comment]
Hi!

Nice find! Yes, that would be the relevant setting for this. Good to hear that everything is working again!

Best wishes,
Tobias
