### ISSUE TITLE
Deprecation error from Freemius

### ISSUE THREAD

**Issue by rubas** [TablePress/TablePress#196]
The included library `Freemius` produces deprecation error as this function can return `null`, which gets picket up by `wp_normalize_path` and `wp_is_stream`.

Reference: https://github.com/TablePress/TablePress/blob/main/libraries/freemius/includes/supplements/fs-essential-functions-1.1.7.1.php#L42

```
ErrorException: Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
#14 /wp/wp-includes/functions.php(2187): wp_normalize_path
#13 /wp/wp-includes/plugin.php(769): plugin_basename
#12 /app/mu-plugins/tablepress/libraries/freemius/start.php(181): require_once
#11 /app/mu-plugins/tablepress/tablepress.php(62): tb_tp_fs
#10 /app/mu-plugins/tablepress/tablepress.php(93): include_once
```

```
ErrorException: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
#15 /wp/wp-includes/functions.php(7288): wp_is_stream
#14 /wp/wp-includes/functions.php(2180): wp_normalize_path
#13 /wp/wp-includes/plugin.php(769): plugin_basename
#12 /app/mu-plugins/tablepress/libraries/freemius/start.php(181): require_once
#11 /app/mu-plugins/tablepress/tablepress.php(62): tb_tp_fs
#10 /app/mu-plugins/tablepress/tablepress.php(93): include_once
```

**Comment by TobiasBg** [comment]
Hi @rubas,

Thanks for also opening this issue in the Freemius repo! As this is where this needs to be fixed, I'll close this issue.
Once an updated version is available, that will be integrated into TablePress as well.

Best wishes,
Tobias

**Comment by rubas** [comment]
Hi @TobiasBg 

there are a ton of similar issue open in the Freemius repo. I'm not sure, when those will be picked up and fixed...

As you are bundling and shipping the library with your plugin, it is - in my humble opinion - also in your responsibility to stay on top of this. Either in patching your shipped version or replacing it with alternatives.

We are not getting anything from the library Freemium, and honestly I would want this code to be part of our installation.

👉🏻 I ask you kindly to stay on top of it and find a solution as I don't have a lot of trust in this being fixed upstream in a reasonable timeframe.

Thanks.

**Comment by TobiasBg** [comment]
Hi @rubas,

Thanks for your feedback on this! From what I know, a rewrite and simplification in that SDK is already being worked on, also with improved compatibility with modern versions of PHP.

Now, what I find a bit confusing is why you are actually getting or seeing this deprecation error. So far, I have no been able to trigger that on my test sites... So, why is `fs_find_direct_caller_plugin_file()` returning `null` for you? Are you using a special setup for your plugins, like symlinking them or something like that?

Best wishes,
Tobias

**Comment by rubas** [comment]
Thanks.

Correct, our setup includes symlink. Those are handled by the plugin, it just returns `null` and this is picked up by the wp hooks, which later results in the warnings.

But I wasn't very keen to debug this further as this is a commercial product and not in any way related to the plugin functionality itself.

**Comment by TobiasBg** [comment]
Hi,

ok, thanks for the those details. I'm also using symlinks for plugins while testing, but I guess that there are different possibilities and yours might not be picked up properly.

I will escalate this again with Freemius, but at this time don't have a solution, sorry. :-(

Best wishes,
Tobias

**Comment by rubas** [comment]
_Bump_
