### ISSUE TITLE
TablePress and Elementor conflict after recent updates, preventing Elementor editor to load

### ISSUE THREAD

**Issue by codeasim** [TablePress/TablePress#197]
TablePress and Elementor conflict after recent updates, preventing Elementor editor to load.

**Comment by TobiasBg** [comment]
Hi @codeasim,

Can you please provide more details here? What exactly is not working? Can you maybe share any error messages (also e.g. in the browser's error log console or screenshots of what you are seeing?

Best wishes,
Tobias
