### ISSUE TITLE
Undefined array key in class-fremius.php:4232

### ISSUE THREAD

**Issue by MacGyer** [TablePress/TablePress#199]
When CLI scripts run, an error is thrown:

PHP Warning:  Undefined array key "HTTP_HOST" in /path/to/tablepress/libraries/freemius/includes/class-freemius.php on line 4232

https://github.com/TablePress/TablePress/blob/387b3b1d16017c65900e3b5ace72fef7cc755477/libraries/freemius/includes/class-freemius.php#L4232

- WP: 6.6.x
- TablePress: 2.4
- OS: Linux Mint 20.3
- PHP: 8.1.x

**Comment by TobiasBg** [comment]
Hi @MacGyer!

Thanks for the report! This is an issue in an external SDK library, and needs to be fixed there.
I have created a new issue based on your report upstream: https://github.com/Freemius/wordpress-sdk/issues/731

Best wishes,
Tobias
