### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fritzi1302** [TablePress/TablePress#202]
Hello im getting following error. 

Fatal error: Uncaught Error: Call to a member function render() on null in /var/www/html/wp-content/plugins/tablepress/controllers/controller-admin.php:671 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(324): TablePress_Admin_Controller->show_admin_page() #1 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /var/www/html/wp-admin/admin.php(259): do_action() #4 {main} thrown in /var/www/html/wp-content/plugins/tablepress/controllers/controller-admin.php on line 671

Wordpress: 6.6.2
PHP: 8.2.20
thanks

**Comment by TobiasBg** [comment]
Hi @fritzi1302,

Thanks for your report. This error is quite strange, I can't directly see how this can happen.
Which TablePress version is this? And when exactly are you getting this error? What's the URL this happens on?

Just to be sure that this is not from corrupt installation, where a file might be missing: Can you please try again after re-installing TablePress from a fresh download? (No worries, your tables and settings will of course be kept!)
If the error persists after that, can you please also try again after temporarily deactivating all other plugins and after switching to a WordPress default theme like Twenty Twenty-Four? That way, we can find what's causing this.

Best wishes,
Tobias

**Comment by fritzi1302** [comment]
Hello, I have version 2.4.2, the latest version, and when I try to activate the plugin after installing it, I get an error. Reinstalling it unfortunately doesn't fix it.

**Comment by TobiasBg** [comment]
Hi @fritzi1302,

okay, that's strange. Did anything change after temporarily deactivating other plugins?
If possible, I'd like to investigate this some more. Can you maybe get in touch via email, via the "Send us an email!" button at the bottom of https://tablepress.org/pricing/?

Best wishes,
Tobias

**Comment by fritzi1302** [comment]
Hi, 

Ich habe gerade gesehn das du auch deutsch sprichst dann würde es vl einwenig einfacher werden, wo findenich euere mailadresse

Lg

**Comment by fritzi1302** [comment]
Oh hab ich gefunden schreib dir per mail

**Comment by TobiasBg** [comment]
Hi!

For anybody finding this thread: On the site in question, the issue is caused by the "WP Custom Admin Interface" plugin. After deactivating that, everything is running fine again.

Best wishes,
Tobias
