### ISSUE TITLE
Gelöst: Das Plugin kann nicht aktiviert werden, da es einen fatalen Fehler erzeugt.

### ISSUE THREAD

**Issue by Heinz53** [TablePress/TablePress#207]
Ich versuche das Plugin direkt im Wordpress über "Neues Plugin hinzufügen" zu installieren.
Beim Aktivieren wird der Fehler "Das Plugin kann nicht aktiviert werden, da es einen fatalen Fehler erzeugt." ausgegeben.

Wordpress wird lokal in einem Docker Container ausgeführt.
Wordpress Version: 6.2
PHP: 8.0.28
mysql: 5.7.42

Folgende Daten wurden nach Docker übertragen
![image](https://github.com/user-attachments/assets/8efb3baa-5c01-42c4-b915-65a4b2c998a9)

Wie kann das Problem gelöst werden?
Vielen Dank für Hinweise
Heinz

**Comment by TobiasBg** [comment]
Hallo @Heinz53,

deinem Screenshot nach zu urteilen fehlen hier mehrere Ordner und Dateien des Plugins. Vermutlich war die Installation bzw. das Kopieren der Dateien unvollständig.
Bitte probiere daher einfach nochmal, TablePress neu herunterzuladen und nochmal zu installieren.

Viele Grüße
Tobias

**Comment by Heinz53** [comment]
Hallo @TobiasBg,
Danke für die Info.
Nach dem löschen des Plugin erhalte ich bei der Installation die folgende Fehlermeldung:


Installation fehlgeschlagen: Das Paket konnte nicht installiert werden. PCLZIP_ERR_MISSING_FILE (-4) : Missing archive file '/tmp/tablepress.2.4.4.zip'

Was kann ich machen?
Viele Grüße
Heinz

**Comment by TobiasBg** [comment]
Hallo @Heinz53,

das ist eine Fehlermeldung von WordPress, hier scheint etwas mit den Upload- und temporären Pfaden in deiner Installation nicht zu stimmen. Leider kann ich damit nicht wirklich weiterhelfen, sorry.

Hast du denn schon probiert, direkt über die "Plugins"-Seite im Dashboard zu installieren, dann brauchst du nicht mit der ZIP-Datei zu hantieren. Ansonsten könntest du auch die ZIP-Datei lokal installieren und den `tablepress`-Ordner in den `wp-content`-Ordner packen.

Viele Grüße
Tobias

**Comment by Heinz53** [comment]
Danke@TobiasBg

Der Fehler kam bei dem Versuch direkt über die "Plugins"-Seite im Dashboard zu installieren.

Nach dem Download der zip Datei konnte ich das Plugin installieren und aktivieren.
Vielen Dank für die Unterstützung
Heinz

**Comment by TobiasBg** [comment]
Hallo @Heinz53,

prima! Schön, dass es jetzt geht!

Viele Grüße
Tobias

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
