### ISSUE TITLE
aria-disabled on ellipsis span in pagination not allowed

### ISSUE THREAD

**Issue by Htbaa** [TablePress/TablePress#213]
The table pagination will show an ellipsis when there are many pages. This span-element has an `aria-disabled="true"` attribute, but this attribute isn't allowed on a span. You should leave it out. If the goal is to have screen readers ignore it apply an `aria-hidden="true"` instead.

This is with v3.

**Comment by TobiasBg** [comment]
Hi @Htbaa,

Thanks for opening this issue! The pagination is a feature that is being added by the external DataTables JavaScript library.
I can not directly influence that, so maybe you can report this in the DataTables GitHub repo https://github.com/DataTables/DataTablesSrc? Thanks!

Best wishes,
Tobias

**Comment by Htbaa** [comment]
Thanks, I've opened an issue there.

**Comment by TobiasBg** [comment]
Hi @Htbaa,

Great, thanks a lot!

Best wishes,
Tobias
